export const HOST_PROTOCOL = [
  "# host/protocol.py",
  '"""ASCII UART framing for the pan/tilt tracker. $payload*CS\\\\r\\\\n"""',
  "from __future__ import annotations",
  "",
  "def xor_checksum(payload: str) -> str:",
  "    cs = 0",
  "    for ch in payload:",
  "        cs ^= ord(ch) & 0xFF",
  '    return f"{cs:02X}"',
  "",
  "",
  "def frame(payload: str) -> str:",
  '    return f"${payload}*{xor_checksum(payload)}\\r\\n"',
  "",
  "",
  "def encode_target(x: float, y: float, timestamp: int) -> str:",
  "    x = max(-1.0, min(1.0, float(x)))",
  "    y = max(-1.0, min(1.0, float(y)))",
  '    return frame(f"T,{x:.3f},{y:.3f},{int(timestamp)}")',
  "",
  "",
  "def encode_stop() -> str:",
  '    return frame("S")',
  "",
  "",
  "def parse_packet(raw: str) -> dict:",
  "    s = raw.strip()",
  '    if not s.startswith("$") or "*" not in s:',
  '        raise ValueError("missing frame")',
  '    payload, cs = s[1:].rsplit("*", 1)',
  "    if xor_checksum(payload) != cs.upper():",
  '        raise ValueError("bad checksum")',
  '    fields = payload.split(",")',
  "    kind = fields[0]",
  '    if kind == "T":',
  "        x, y, ts = float(fields[1]), float(fields[2]), int(float(fields[3]))",
  "        if not (-1.0 <= x <= 1.0 and -1.0 <= y <= 1.0):",
  '            raise ValueError("out of range")',
  '        return {"kind": "T", "x": x, "y": y, "timestamp": ts}',
  '    if kind in {"S", "H", "E"}:',
  '        return {"kind": kind}',
  '    if kind == "A":',
  '        return {"kind": "A", "ok": fields[1] == "1"}',
  '    raise ValueError("unknown type")',
].join("\n");

export const HOST_TRACKER = [
  "# host/tracker.py",
  "from __future__ import annotations",
  "",
  "def compute_normalized_error(tx, ty, width, height, deadband=0.0):",
  "    cx, cy = width / 2.0, height / 2.0",
  "    nx = max(-1.0, min(1.0, (tx - cx) / (width / 2.0)))",
  "    ny = max(-1.0, min(1.0, (ty - cy) / (height / 2.0)))",
  "    in_band = abs(nx) < deadband and abs(ny) < deadband",
  "    return nx, ny, in_band",
  "",
  "",
  "def exp_smooth(prev, sample, alpha):",
  "    a = max(0.0, min(1.0, alpha))",
  "    return a * sample + (1.0 - a) * prev",
  "",
  "",
  "def apply_deadband(value, deadband):",
  "    return 0.0 if abs(value) < deadband else value",
].join("\n");

export const HOST_CONTROLLER = [
  "# host/controller.py",
  "from __future__ import annotations",
  "",
  "class PID:",
  "    def __init__(self, kp=1.0, ki=0.0, kd=0.0):",
  "        self.kp, self.ki, self.kd = kp, ki, kd",
  "        self.integral = 0.0",
  "        self.prev = 0.0",
  "        self.ready = False",
  "",
  "    def update(self, error, dt, deadband=0.0):",
  "        e = 0.0 if abs(error) < deadband else error",
  "        p = self.kp * e",
  "        d = 0.0",
  "        if self.ready and dt > 1e-6:",
  "            d = self.kd * (e - self.prev) / dt",
  "        tentative = self.integral + e * dt",
  "        out = max(-1.0, min(1.0, p + self.ki * tentative + d))",
  "        saturated = out in (-1.0, 1.0)",
  "        winding = (e > 0 and out > 0) or (e < 0 and out < 0)",
  "        if not (saturated and winding):",
  "            self.integral = max(-2.0, min(2.0, tentative))",
  "        out = max(-1.0, min(1.0, p + self.ki * self.integral + d))",
  "        self.prev, self.ready = e, True",
  "        return out",
].join("\n");

export const FIRMWARE_PROTOCOL = [
  "/* firmware/App/protocol.c — XOR ASCII parser */",
  '#include "protocol.h"',
  "#include <string.h>",
  "#include <stdlib.h>",
  "",
  "uint8_t protocol_checksum(const char *payload, uint16_t len) {",
  "    uint8_t cs = 0;",
  "    for (uint16_t i = 0; i < len; i++) cs ^= (uint8_t)payload[i];",
  "    return cs;",
  "}",
  "",
  "static int hex_nibble(char c) {",
  "    if (c >= '0' && c <= '9') return c - '0';",
  "    if (c >= 'A' && c <= 'F') return 10 + c - 'A';",
  "    if (c >= 'a' && c <= 'f') return 10 + c - 'a';",
  "    return -1;",
  "}",
  "",
  "bool protocol_parse(const char *raw, protocol_packet_t *out) {",
  "    if (!raw || raw[0] != '$') return false;",
  "    const char *star = strrchr(raw, '*');",
  "    if (!star || star <= raw + 1) return false;",
  "    uint16_t len = (uint16_t)(star - raw - 1);",
  "    if (len >= PROTOCOL_MAX_PAYLOAD) return false;",
  "    int hi = hex_nibble(star[1]);",
  "    int lo = hex_nibble(star[2]);",
  "    if (hi < 0 || lo < 0) return false;",
  "    uint8_t got = (uint8_t)((hi << 4) | lo);",
  "    if (got != protocol_checksum(raw + 1, len)) return false;",
  "",
  "    char buf[PROTOCOL_MAX_PAYLOAD];",
  "    memcpy(buf, raw + 1, len);",
  "    buf[len] = 0;",
  "    memset(out, 0, sizeof(*out));",
  "    out->type = buf[0];",
  "",
  "    if (buf[0] == 'T') {",
  "        char *p = buf + 2;",
  "        out->x = strtof(p, &p);",
  "        if (*p != ',') return false;",
  "        out->y = strtof(p + 1, &p);",
  "        if (*p != ',') return false;",
  "        out->timestamp = (uint32_t)strtoul(p + 1, NULL, 10);",
  "        if (out->x < -1.f || out->x > 1.f || out->y < -1.f || out->y > 1.f)",
  "            return false;",
  "        return true;",
  "    }",
  "    return buf[0] == 'S' || buf[0] == 'H' || buf[0] == 'E' || buf[0] == 'A';",
  "}",
].join("\n");

export const FIRMWARE_MOTOR = [
  "/* firmware/Drivers/motor.c — accel-limited STEP/DIR */",
  '#include "motor.h"',
  "",
  "static float clampf(float v, float lo, float hi) {",
  "    if (v < lo) return lo;",
  "    if (v > hi) return hi;",
  "    return v;",
  "}",
  "",
  "void motor_step(motor_axis_t *ax, float dt) {",
  "    if (!ax->enabled) {",
  "        ax->current_vel = 0.f;",
  "        ax->target_vel = 0.f;",
  "        return;",
  "    }",
  "    float target = clampf(ax->target_vel, -ax->max_speed, ax->max_speed);",
  "    float max_dv = ax->acceleration * dt;",
  "    float dv = target - ax->current_vel;",
  "    if (dv > max_dv) dv = max_dv;",
  "    if (dv < -max_dv) dv = -max_dv;",
  "    ax->current_vel = clampf(ax->current_vel + dv, -ax->max_speed, ax->max_speed);",
  "    ax->position_deg += ax->current_vel * dt;",
  "    if (ax->position_deg > ax->limit_deg) {",
  "        ax->position_deg = ax->limit_deg;",
  "        if (ax->current_vel > 0) ax->current_vel = 0;",
  "    } else if (ax->position_deg < -ax->limit_deg) {",
  "        ax->position_deg = -ax->limit_deg;",
  "        if (ax->current_vel < 0) ax->current_vel = 0;",
  "    }",
  "}",
].join("\n");

export const FIRMWARE_CONFIG = [
  "/* firmware/config/hardware_config.h */",
  "#pragma once",
  "",
  "#define PAN_STEP_PIN          GPIO_PIN_0",
  "#define PAN_STEP_PORT         GPIOA",
  "#define PAN_DIR_PIN           GPIO_PIN_1",
  "#define PAN_DIR_PORT          GPIOA",
  "#define PAN_ENABLE_PIN        GPIO_PIN_2",
  "#define PAN_ENABLE_PORT       GPIOA",
  "",
  "#define TILT_STEP_PIN         GPIO_PIN_3",
  "#define TILT_STEP_PORT        GPIOA",
  "#define TILT_DIR_PIN          GPIO_PIN_4",
  "#define TILT_DIR_PORT         GPIOA",
  "#define TILT_ENABLE_PIN       GPIO_PIN_5",
  "#define TILT_ENABLE_PORT      GPIOA",
  "",
  "#define UART_INSTANCE         USART1",
  "#define UART_BAUD             115200",
  "#define UART_TX_PIN           GPIO_PIN_9",
  "#define UART_RX_PIN           GPIO_PIN_10",
  "#define UART_PORT             GPIOA",
  "",
  "#define LIMIT_PAN_MIN_PIN     GPIO_PIN_6",
  "#define LIMIT_PAN_MAX_PIN     GPIO_PIN_7",
  "#define LIMIT_TILT_MIN_PIN    GPIO_PIN_8",
  "#define ENABLE_ACTIVE_LOW     1",
].join("\n");

export const FILES = [
  { id: "protocol.py", title: "host/protocol.py", lang: "python", body: HOST_PROTOCOL },
  { id: "tracker.py", title: "host/tracker.py", lang: "python", body: HOST_TRACKER },
  { id: "controller.py", title: "host/controller.py", lang: "python", body: HOST_CONTROLLER },
  { id: "protocol.c", title: "firmware/App/protocol.c", lang: "c", body: FIRMWARE_PROTOCOL },
  { id: "motor.c", title: "firmware/Drivers/motor.c", lang: "c", body: FIRMWARE_MOTOR },
  { id: "hardware_config.h", title: "firmware/config/hardware_config.h", lang: "c", body: FIRMWARE_CONFIG },
] as const;
